#include "main.h"







#define IN0_GPIO_PORT GPIOA
#define IN0_PIN GPIO_PIN_0

#define IN1_GPIO_PORT GPIOA
#define IN1_PIN GPIO_PIN_1

#define IN2_GPIO_PORT GPIOA
#define IN2_PIN GPIO_PIN_5

#define IN3_GPIO_PORT GPIOA
#define IN3_PIN GPIO_PIN_4








#define IN4_GPIO_PORT GPIOB
#define IN4_PIN GPIO_PIN_7

#define IN5_GPIO_PORT GPIOB
#define IN5_PIN GPIO_PIN_6

#define IN6_GPIO_PORT GPIOB
#define IN6_PIN GPIO_PIN_4

#define IN7_GPIO_PORT GPIOB
#define IN7_PIN GPIO_PIN_5


#define STATE_GPIO_PORT GPIOB
#define STATE_PIN GPIO_PIN_8







#define LD1_GPIO_PORT GPIOB
#define LD1_PIN GPIO_PIN_13

#define LD2_GPIO_PORT GPIOB
#define LD2_PIN GPIO_PIN_14

#define LD3_GPIO_PORT GPIOB
#define LD3_PIN GPIO_PIN_15

#define LD4_GPIO_PORT GPIOA
#define LD4_PIN GPIO_PIN_8



#define SW1_GPIO_PORT GPIOA
#define SW1_PIN GPIO_PIN_7

#define SW2_GPIO_PORT GPIOB
#define SW2_PIN GPIO_PIN_0

#define SW3_GPIO_PORT GPIOB
#define SW3_PIN GPIO_PIN_1

#define SW4_GPIO_PORT GPIOB
#define SW4_PIN GPIO_PIN_12









#define IN0(x) x ? HAL_GPIO_WritePin(IN0_GPIO_PORT, IN0_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN0_GPIO_PORT, IN0_PIN, GPIO_PIN_RESET)
#define IN1(x) x ? HAL_GPIO_WritePin(IN1_GPIO_PORT, IN1_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN1_GPIO_PORT, IN1_PIN, GPIO_PIN_RESET)
#define IN2(x) x ? HAL_GPIO_WritePin(IN2_GPIO_PORT, IN2_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN2_GPIO_PORT, IN2_PIN, GPIO_PIN_RESET)
#define IN3(x) x ? HAL_GPIO_WritePin(IN3_GPIO_PORT, IN3_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN3_GPIO_PORT, IN3_PIN, GPIO_PIN_RESET)



#define IN4(x) x ? HAL_GPIO_WritePin(IN4_GPIO_PORT, IN4_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN4_GPIO_PORT, IN4_PIN, GPIO_PIN_RESET)
#define IN5(x) x ? HAL_GPIO_WritePin(IN5_GPIO_PORT, IN5_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN5_GPIO_PORT, IN5_PIN, GPIO_PIN_RESET)
#define IN6(x) x ? HAL_GPIO_WritePin(IN6_GPIO_PORT, IN6_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN6_GPIO_PORT, IN6_PIN, GPIO_PIN_RESET)
#define IN7(x) x ? HAL_GPIO_WritePin(IN7_GPIO_PORT, IN7_PIN, GPIO_PIN_SET) :	HAL_GPIO_WritePin(IN7_GPIO_PORT, IN7_PIN, GPIO_PIN_RESET)



#define LD1(x) x ? HAL_GPIO_WritePin(LD1_GPIO_PORT, LD1_PIN , GPIO_PIN_RESET) :  HAL_GPIO_WritePin(LD1_GPIO_PORT, LD1_PIN , GPIO_PIN_SET)
#define LD2(x) x ? HAL_GPIO_WritePin(LD2_GPIO_PORT, LD2_PIN , GPIO_PIN_RESET) :  HAL_GPIO_WritePin(LD2_GPIO_PORT, LD2_PIN , GPIO_PIN_SET)
#define LD3(x) x ? HAL_GPIO_WritePin(LD3_GPIO_PORT, LD3_PIN , GPIO_PIN_RESET) :  HAL_GPIO_WritePin(LD3_GPIO_PORT, LD3_PIN , GPIO_PIN_SET)
#define LD4(x) x ? HAL_GPIO_WritePin(LD4_GPIO_PORT, LD4_PIN , GPIO_PIN_RESET) :  HAL_GPIO_WritePin(LD4_GPIO_PORT, LD4_PIN , GPIO_PIN_SET)





